name: RoCrate to GitHub Pages
on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
  pull_request:
jobs:
  update-rocrate:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      # Checkout this repo
      - uses: actions/checkout@v3 
      
      # Build the preview.html file from the rocrate.json
      - name: Rocrate fixer
        uses: vliz-be-opsci/rocrate-fix@latest
        with:
          extra_metadata: extra_metadata.json
 
      - name: git-auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v4
  build-html:
    needs: update-rocrate
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: rocrate-to-pages
        uses: vliz-be-opsci/rocrate-to-pages@latest
        with:
          multiple_rocrates: true
          release_management: false
          include_draft: false
          index_html: false
          space_to_pages_homepage: https://data.arms-mbon.org/
      - name: actions-gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./unicornpages
